steps:
  - name: 'maven:3-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: [ 'test' ]
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'functions',
            'deploy',
            '${REPO_NAME}',
            '--runtime=java17',
            '--region=europe-west1',
            '--source=.' ]