steps:
  - name: 'maven:3-jdk-11'
    entrypoint: 'mvn'
    args: [ 'test' ]
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'functions','deploy','${REPO_NAME}','--region=europe-west1','--source=.' ]